# Generated by Django 5.2.4 on 2025-08-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('category', models.CharField(choices=[('pen', 'Pen'), ('pencil', 'Pencil'), ('eraser', 'Eraser'), ('scale', 'Scale'), ('pouch', 'Pouch'), ('keychain', 'Keychain'), ('others', 'Others')], max_length=20)),
            ],
        ),
    ]
