# Generated by Django 5.2.4 on 2025-08-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moss', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('pen', 'Pen'), ('pencil', 'Pencil'), ('eraser', 'Eraser'), ('scale', 'Scale'), ('pouch', 'Pouch'), ('keychain', 'Keychain'), ('book', 'Book'), ('others', 'Others')], max_length=20),
        ),
    ]
